Enumerables branch
aracelicaes/my-enumerables pull request #3
Opened 2020-01-30 19:23 UTC by aracelicaes

Pull request #1 for my enumerables-branch

2020-02-20 18:42 UTC, Forison requested changes
## Status: Require changes🛑
# 🙋‍♂️ Ara,
You have done a good job on this one. There is an issue with ``my_all``, let us fix it.
### check below the comments 👇👇👇 for the areas you have to improve.
## That is it kindly make the change and submit the project for review🙂
#### Happy coding💻
#### Addo Forison

2020-02-20 18:42 UTC, Forison commented on ara_enumerables.rb
> +    return to_enum unless block_given?
#### [optional]
Pass the method name as an argument to ```to_enum``` like you have done for my_each to make your method more customized.
``` return to_enum(:my_each_with_index) unless block_given?```

2020-02-20 18:42 UTC, Forison commented on ara_enumerables.rb
> +  def my_all?(arg = nil)
* [ ] should have working my_all? identical and returns the same thing as ruby's all?.  ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
let us fix this
```p [1, 2i, 3.14].my_all?(Numeric)  != p [1, 2i, 3.14].all?(Numeric)```

2020-02-20 18:42 UTC, Forison commented on ara_enumerables.rb
> +    return to_enum unless block_given?
#### [optional]
Pass the method name as an argument to ```to_enum``` like you have done for my_each to make your method more customized.
``` return to_enum(:my_select) unless block_given?```

2020-02-21 10:49 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good job implementing changes suggested by @Forison 

Check out the optional comments before merging. :relaxed: 

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-02-21 10:49 UTC, bolah2009 commented on utils.rb
> +end
This method seems to be adding the first value of the array two times when no initial value is given in the `inject` method.

```ruby
irb(main):002:0> [1,2,3,4,5,56,7,8,9,234].inject(:+)
#=> 329
irb(main):003:0> [1,2,3,4,5,56,7,8,9,234].my_inject(:+)
#=> 330

irb(main):005:0> [19,2,3,4,5,56,7,8,9,234].inject(:+)
#=> 347
irb(main):006:0> [19,2,3,4,5,56,7,8,9,234].my_inject(:+)
#=> 366
```

2020-02-24 14:21 UTC, merged